# Generated by Django 3.2.7 on 2021-10-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
