# Generated by Django 3.2.7 on 2021-10-01 18:52

import EcommerceApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApi', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=EcommerceApi.models.generate_isbn, max_length=13),
        ),
    ]
