# Generated by Django 3.2.7 on 2021-10-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApi', '0004_auto_20211002_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-price',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-price',)},
        ),
    ]
